# Forest Fire simulation parameters
size: 42
alpha: 5
beta: 6
delta_beta: 10
alpha_wind: 0
wind_x: 0
wind_y: 0
memoryless: false
# simulation parameters
timesteps: 0  # 0 for full simulation
agents: 8
# general setup
gui: Yes
mode: Haksar  # Haksar, Heuristic or user (for user defined algorithm)
logfile: No
grid: hexagonal # hexagonal or rectangular
# success metric weights
healthy: 0.6
extinguished : 0.2
time: 0.2
