# Forest Fire simulation parameters
size: 22
alpha: 7
beta: 4
delta_beta: 10
# simulation parameters
timesteps: 0  # 0 for full simulation
agents: 3
# general setup
gui: True
mode: Haksar
logfile: No
grid: hexagonal  # hexagonal or rectangular
# success metric weights
healthy: 0.6
extinguished : 0.2
time: 0.2
