# Forest Fire simulation parameters
size: 42
alpha: 7
beta: 7
delta_beta: 10
# simulation parameters
timesteps: 2  # 0 for full simulation
agents: 0
# general setup
gui: Yes
mode: Haksar  # Haksar, Heuristic or user (for user defined algorithm)
logfile: No
grid: rectangular # hexagonal or rectangular
# success metric weights
healthy: 0.6
extinguished : 0.2
time: 0.2
